repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
        exclude: ^lib/
      - id: check-toml
      - id: trailing-whitespace
        files: ^lib/
      - id: end-of-file-fixer
        files: ^lib/
      - id: mixed-line-ending
      - id: detect-private-key

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: "v4.7.0"
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [pre-commit, pre-push]

  - repo: https://github.com/fluttercommunity/import_sorter
    rev: "641f363d40a4ffb42ab577a43433fc48c5059b19"
    hooks:
      - id: flutter-import-sorter
